"""Added required tables fix

Revision ID: 406e9134e2f6
Revises: e499bb42da21
Create Date: 2021-10-25 15:11:43.992746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406e9134e2f6'
down_revision = 'e499bb42da21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'accounts', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'created_by')
    # ### end Alembic commands ###
